x = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(x))
print('É alfabético?', x.isalpha())
print('É um número?', x.isnumeric())
print('É alfanumérico?', x.isalnum())
print('Está em letras minúsculas?', x.islower())
print('Está em letras maiúsculas?', x.isupper())
print('É copiável?', x.isprintable())
print('Tem somente espaços?', x.isspace())
print('Está capitalizada?', x.istitle())
